# config/routes.yaml
login:
    path:       /security/login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
    
after_login:
    path:       /security/after/login
    controller: App\Controller\SecurityController::after_login
    schemes:    [https]

